version: 2.1
orbs:
    codecov: codecov/codecov@3.2.2
    browser-tools: circleci/browser-tools@1.2.4
jobs:
  build_demo:
    docker:
      - image: cimg/node:14.19.0-browsers
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - restore_cache:
          keys:
            - v2-dependencies-angular-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: |
            yarn install --frozen-lockfile
      - save_cache:
          name: Save Cache
          paths:
            - /node_modules
          key: v2-dependencies-angular-{{ checksum "yarn.lock" }}
      - run:
          name: Prettier Check
          command: |
            yarn prettier:check
      - run:
          name: Lint
          command: |
            yarn lint
      - run:
          name: Unit Test
          command: |
            yarn test --no-watch --code-coverage
      - run:
            name: Build Demo
            command: |
                yarn build
      # Save the coverage folder for codecov report upload.
      - persist_to_workspace:
            root: .
            paths:
                - coverage
  coverage_report:
        working_directory: ~/angular-showcase-demo
        docker:
            - image: cimg/node:14.19.0-browsers
        steps:
            - checkout
            - attach_workspace:
                at: .
            - codecov/upload:
                file: './coverage/lcov.info'
                token: CODECOV_TOKEN

workflows:
  version: 2
  angular_demo:
    jobs:
      - build_demo
      - coverage_report:
                requires:
                    - build_demo
                filters:
                    branches:
                        only:
                            - master
